version: '2'
services:
   mosquitto:
      image: eclipse-mosquitto
      ports:
         - "1883:1883"
         - "9001:9001"
      volumes:
         - ./mosquitto:/mosquitto/data
   node-red:
      build: ./node-red
      ports:
         - "1880:1880"
      volumes:
         - ./node-red/data:/data
   influxdb:
      image: tutum/influxdb
      ports:
         - "8083:8083"
         - "8086:8086"
      volumes:
         - ./influxdb:/var/lib/influxdb
      environment:
         PRE_CREATE_DB: metrics
   chronograf:
      image: chronograf
      ports: 
         - "10000:10000"
      volumes:
         - ./chronograf:/var/lib/chronograf
      environment:
         CHRONOGRAF_LOCAL_DATABASE: /var/lib/chronograf/chronograf.db

volumes:
   mosquitto:
   node-red:
   influxdb:
   chronograf: